### ISSUE TITLE
How to use stock_barcode module

### ISSUE THREAD

**Issue by rrafik** [sekawe/arodoo_stock_barcode#1]
Hi M. Mahmoud

i install the module but nothing happening when i scan barcodes in piching.

please how to use this module? there is any dependencies to install before using the module ?

thank you

**Comment by sekawe** [comment]
Dear rrafik,
Please make sure you got the latest update of the module which should be maximum before 4.

After installing the module, just go to any picking list and scan the barcode label which it's number stored in a product (Barcode field) in the same list.
Please if this didn't work for you let me know so I will explain this in more details.

Hope everything work fine with you.

Best Regards,
Mahmoud Al Shaikh

**Comment by mahmoud-alshaikh** [comment]
@rrafik Please let me know if your issue has been solved.

**Comment by sekawe** [comment]
@rrafik Please let me know if your issue has been solved.

**Comment by rrafik** [comment]
Hi M. Mahmoud

First, excuse me for the delay and thank you for your replay.

i still have the same probleme.

This is what I did.

1. Download the latest version (4) and install it in a new database.
2. Create some products with barcode information
3. Create a new picking document
    a. Select a partner and scheduled date
    b. Select picking type (receipts)
4. Scan barcode
     a.	When I am in edit mode and I scan, nothing’s happened. 
     b.	But when I am in no edit mode and I scan, I have a Odoo message telling (to modify this document, please start edition)

Note : I use a odoo 10 community edition and arodoo_stock_barcode for odoo 10.
 
What I can check also ?

Best Regards.

**Comment by sekawe** [comment]
@rrafik Based on your scenario, it should be working. Make sure the scanned barcode is the same barcode stored in product form.

In addition, I will make a simple article describes how to use this module.

Thanks.

**Comment by rrafik** [comment]
ok, i will do it.

Thank you.
